env:
  global:
    - CC_TEST_REPORTER_ID=2eb79c71ae885575fdc12f9779d6c463241b807acf8caace9a0edbb0434f197f
# Project language
language: php

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Settings version PHP
php:
  - 7.1
  - 7.2

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- mv phpunit.xml.dist phpunit.xml
- ./cc-test-reporter before-build

# Run script
script:
  - ./bin/phpunit --coverage-clover clover.xml

after_script:
- ./cc-test-reporter after-build --debug --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT