version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: training.mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
    volumes:
      - /var/lib/mysql